eureka:
  client:
    register-with-eureka: false

server:
  port: 8222
spring:
  application:
    name: gateway
 # config:
  #  import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:8890
            predicates:
              - Path=/api/students/**
          - id: schools
            uri: http://localhost:8891
            predicates:
              - Path=/api/schools/**

