eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      deafaultZone: http://localhost:8761/eureka

server:
  port: 8891
spring:
  application:
    name: schools
  #config:
   # import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shcools
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      name: school-topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
